export const STATE_PATH = 'speakeasyapp';
export const MAXIMUM_PAYLOAD_BLOCK_SIZE = 725;

export const DUMMY_TRAFFIC_MAXIMUM_MESSAGES_PER_CYCLE = 3;
export const DUMMY_TRAFFIC_DURATION_TO_WAIT_BETWEEN_SENDS_MILLISECONDS = 15000;
export const DUMMY_TRAFFIC_UPPERBOUND_INTERVAL_BETWEEN_CYCLES_MILLISECONDS = 7000;
export const DUMMY_TRAFFIC_ARGS = [
  DUMMY_TRAFFIC_MAXIMUM_MESSAGES_PER_CYCLE,
  DUMMY_TRAFFIC_DURATION_TO_WAIT_BETWEEN_SENDS_MILLISECONDS,
  DUMMY_TRAFFIC_UPPERBOUND_INTERVAL_BETWEEN_CYCLES_MILLISECONDS
]